--[[
@Author: Vogel
@Copyright: Vogel / DiamondMTA // 2020-2021

@Pierwotne prawo do użytku tego skryptu ma TYLKO autor i serwery otrzymujące zgodę na jego użytkowanie przez autora
@Obowiązuje całkowity zakaz rozpowszechniania skryptów, zmiany autora, edycji skryptów bez zgody autora
@Nie masz prawa użytkować tego skryptu bez mojej zgody.
]]--

clothes = {
  ['wlosy'] = {
    {'player_face', 'head'},
    {'hairblond', 'head'},
    {'hairred', 'head'},
    {'hairblue', 'head'},
    {'hairgreen', 'head'},
    {'hairpink', 'head'},
    {'bald', 'head'},
    {'baldbeard', 'head'},
    {'baldtash', 'head'},
    {'baldgoatee', 'head'},
    {'highafro', 'highafro'},
    {'wedge', 'wedge'},
    {'slope', 'slope'},
    {'jhericurl', 'jheri'},
    {'cornrows', 'cornrows'},
    {'cornrowsb', 'cornrows'},
    {'tramline', 'tramline'},
    {'groovecut', 'groovecut'},
    {'mohawk', 'mohawk'},
    {'mohawkblond', 'mohawk'},
    {'mohawpink', 'mohawk'},
    {'mohawkbeard', 'mohawk'},
    {'afro', 'afro'},
    {'afrotash', 'afro'},
    {'afrobeard', 'afro'},
    {'afroblond', 'afro'},
    {'flattop', 'flattop'},
    {'elvishair', 'elvishair'},
    {'beard', 'head'},
    {'tash', 'head'},
    {'goatee', 'head'},
    {'afrogoatee', 'afro'},

    {'bandred', 'bandana'},
    {'bandblue', 'bandana'},
    {'bandgang', 'bandana'},
    {'bandblack', 'bandana'},
    {'bandred2', 'bandknots'},
    {'bandblue2', 'bandknots'},
    {'banblack2', 'bandknots'},
    {'bandgang2', 'bandknots'},
    {'capknitgrn', 'capknit'},
    {'captruck', 'captruck'},
    {'cowboy', 'cowboy'},
    {'hattiger', 'cowboy'},
    {'helmet', 'helmet'},
    {'moto', 'moto'},
    {'boxingcap', 'boxingcap'},
    {'hockey', 'hockeymask'},
    {'capgang', 'cap'},
    {'capgangback', 'capback'},
    {'capgangside', 'capside'},
    {'capgangover', 'capovereye'},
    {'capgangup', 'caprimup'},
    {'bikerhelmet', 'bikerhelmet'},
    {'capred', 'cap'},
    {'capredback', 'capback'},
    {'capredside', 'capside'},
    {'capredover', 'capovereye'},
    {'capblue', 'cap'},
    {'capblueback', 'capback'},
    {'capblueside', 'capside'},
    {'capblueover', 'capovereye'},
    {'capblueup', 'caprimup'},
    {'skullyblk', 'skullycap'},
    {'skullygrn', 'skullycap'},
    {'hatmancblk', 'hatmanc'},
    {'hatmancplaid', 'hatmanc'},
    {'capzip', 'cap'},
    {'capzipback', 'capback'},
    {'capzipside', 'capside'},
    {'capzipover', 'capovereye'},
    {'capzipup', 'caprimup'},
    {'beretred', 'beret'},
    {'beretblk', 'beret'},
    {'capblk', 'cap'},
    {'capblkback', 'capback'},
    {'capblkside', 'capside'},
    {'capblkover', 'capovereye'},
    {'capblkup', 'caprimup'},
    {'trillbydrk', 'trillby'},
    {'trillbylght', 'trillby'},
    {'bowler', 'bowler'},
    {'bowlerred', 'bowler'},
    {'bowlerblue', 'bowler'},
    {'bowleryellow', 'bowler'},
    {'boater', 'boater'},
    {'bowlergang', 'bowler'},
    {'boaterblk', 'boater'},
  },

  ['koszulki'] = {
    {'player_torso', 'torso'},
    {'vestblack', 'vest'},
    {'vest', 'vest'},
    {'tshirt2horiz', 'tshirt2'},
    {'tshirtwhite', 'tshirt'},
    {'tshirtilovels', 'tshirt'},
    {'tshirtblunts', 'tshirt'},
    {'shirtbplaid', 'shirtb'},
    {'shirtbcheck', 'shirtb'},
    {'field', 'field'},
    {'tshirterisyell', 'tshirt'},
    {'tshirterisorn', 'tshirt'},
    {'trackytop2eris', 'trackytop1'},
    {'bbjackrim', 'bbjack'},
    {'bballjackrstar', 'bbjack'},
    {'baskballdrib', 'baskball'},
    {'baskballrim', 'baskball'},
    {'sixtyniners', 'tshirt'},
    {'bandits', 'baseball'},
    {'tshirtpored', 'tshirt'},
    {'tshirtporedblk', 'tshirt'},
    {'trackytop1pro', 'trackytop1'},
    {'hockeytop', 'sweat'},
    {'bbjersey', 'sleevt'},
    {'shellsuit', 'trackytop1'},
    {'tshirtheatwht', 'tshirt'},
    {'tshirtbobomonk', 'tshirt'},
    {'tshirtbobred', 'tshirt'},
    {'tshirtbase5', 'tshirt'},
    {'tshirtsuburb', 'tshirt'},
    {'hoodyamerc', 'hoodya'},
    {'hoodyabase5', 'hoodya'},
    {'hoodyarockstar', 'hoodya'},
    {'wcoatblue', 'wcoat'},
    {'coach', 'coach'},
    {'coachsemi', 'coach'},
    {'sweatrstar', 'sweat'},
    {'hoodyAblue', 'hoodyA'},
    {'hoodyAblack', 'hoodyA'},
    {'hoodyAgreen', 'hoodyA'},
    {'sleevtbrown', 'sleevt'},
    {'shirtablue', 'shirta'},
    {'shirtayellow', 'shirta'},
    {'shirtgrey', 'shirta'},
    {'shirtbgang', 'shirtb'},
    {'tshirtzipcrm', 'tshirt'},
    {'tshirtzipgry', 'tshirt'},
    {'denimfade', 'denim'},
    {'bowling', 'hawaii'},
    {'hoodjackbeige', 'hoodjack'},
    {'baskballloc', 'baskball'},
    {'tshirtlocgrey', 'tshirt'},
    {'tshirtmaddgrey', 'tshirt'},
    {'tshirtmaddgrn', 'tshirt'},
    {'suit1grey', 'suit1'},
    {'suit1blk', 'suit1'},
    {'leather', 'leather'},
    {'painter', 'painter'},
    {'hawaiiwht', 'hawaii'},
    {'hawaiired', 'hawaii'},
    {'sportjack', 'trackytop1'},
    {'suit1red', 'suit1'},
    {'suit1blue', 'suit1'},
    {'suit1yellow', 'suit1'},
    {'suit2grn', 'suit2'},
    {'tuxedo', 'suit2'},
    {'suit1gang', 'suit1'},
    {'letter', 'sleevt'},
  },

  ['spodnie'] = {
    {'player_legs', 'legs'},
    {'worktrcamogrn', 'worktr'},
    {'worktrcamogry', 'worktr'},
    {'worktrgrey', 'worktr'},
    {'worktrkhaki', 'worktr'},
    {'tracktr', 'tracktr'},
    {'trackteris', 'tracktr'},
    {'jeansdenim', 'jeans'},
    {'legsblack', 'legs'},
    {'legsheart', 'legs'},
    {'biegetr', 'chinosb'},
    {'tracktrpro', 'tracktr'},
    {'tracktrwhstr', 'tracktr'},
    {'tracktrblue', 'tracktr'},
    {'tracktrgang', 'tracktr'},
    {'bbshortwht', 'boxingshort'},
    {'boxshort', 'boxingshort'},
    {'bbshortred', 'boxingshort'},
    {'shellsuittr', 'tracktr'},
    {'shortsgrey', 'shorts'},
    {'shortskhaki', 'shorts'},
    {'chongergrey', 'chonger'},
    {'chongergang', 'chonger'},
    {'chongerred', 'chonger'},
    {'chongerblue', 'chonger'},
    {'shortsgang', 'shorts'},
    {'denimsgang', 'jeans'},
    {'denimsred', 'jeans'},
    {'chinosbiege', 'chinosb'},
    {'chinoskhaki', 'chinosb'},
    {'cutoffchinos', 'shorts'},
    {'cutoffchinosblue', 'shorts'},
    {'chinosblack', 'chinosb'},
    {'chinosblue', 'chinosb'},
    {'leathertr', 'leathertr'},
    {'leathertrchaps', 'leathertr'},
    {'suit1grey', 'suit1tr'},
    {'suit1trblk', 'suit1tr'},
    {'cutoffdenims', 'short'},
    {'suit1red', 'suit1tr'},
    {'suit1trblue', 'suit1tr'},
    {'suit1tryellow', 'suit1tr'},
    {'suit1trgreen', 'suit1tr'},
    {'suit1trblk2', 'suit1tr'},
    {'suit1trgang', 'suit1tr'},
  },

  ['szyja'] = {
    {'dogtag', 'neck'},
    {'neckafrica', 'neck'},
    {'stopwatch', 'neck'},
    {'necksaints', 'neck'},
    {'neckhash', 'neck'},
    {'necksilver', 'neck2'},
    {'neckgold', 'neck2'},
    {'neckropes', 'neck2'},
    {'neckropeg', 'neck2'},
    {'neckls', 'neck'},
    {'neckdollar', 'neck'},
    {'neckcross', 'neck'},
  },

  ['zegarki'] = {
    {'watchpink', 'watch'},
    {'watchyellow', 'watch'},
    {'watchpro', 'watch'},
    {'watchpro2', 'watch'},
    {'watchsub1', 'watch'},
    {'watchsub2', 'watch'},
    {'watchzip1', 'watch'},
    {'watchzip2', 'watch'},
    {'watchgno', 'watch'},
    {'watchgno2', 'watch'},
    {'watchcro', 'watch'},
    {'watchcro2', 'watch'},
  },

  ['okulary'] = {
    {'groucho', 'groucho'},
    {'zorro', 'zorromask'},
    {'eyepatch', 'eyepatch'},
    {'glasses01', 'glasses01'},
    {'glasses04', 'glasses04'},
    {'bandred3', 'bandmask'},
    {'bandblue3', 'bandmask'},
    {'bandgang3', 'bandmask'},
    {'bandblack3', 'bandmask'},
    {'glasses01dark', 'glasses01'},
    {'glasses04dark', 'glasses04'},
    {'glasses03', 'glasses03'},
    {'glasses03red', 'glasses03'},
    {'glasses03blue', 'glasses03'},
    {'glasses03dark', 'glasses03'},
    {'glasses05dark', 'glasses03'},
    {'glasses05', 'glasses03'},
  },

  ['buty'] = {
    {'foot', 'feet'},
    {'cowboyboot2', 'biker'},
    {'bask2semi', 'bask1'},
    {'bask1eris', 'bask1'},
    {'sneakerbincgang', 'sneaker'},
    {'sneakerbincblue', 'sneaker'},
    {'sneakerbincblk', 'sneaker'},
    {'sandal', 'flipflop'},
    {'sandalsock', 'flipflop'},
    {'flipflop', 'flipflop'},
    {'hitop', 'bask1'},
    {'convproblk', 'conv'},
    {'convproblu', 'conv'},
    {'convprogrn', 'conv'},
    {'sneakerprored', 'sneaker'},
    {'sneakerproblu', 'sneaker'},
    {'sneakerprowht', 'sneaker'},
    {'bask1prowht', 'bask1'},
    {'bask1problk', 'bask1'},
    {'boxingshoe', 'biker'},
    {'convheatblk', 'conv'},
    {'convheatred', 'conv'},
    {'convheatorn', 'conv'},
    {'sneakerheatwht', 'sneaker'},
    {'sneakerheatgry', 'sneaker'},
    {'sneakerheatblk', 'sneaker'},
    {'bask2heatwht', 'bask1'},
    {'bask2heatband', 'bask1'},
    {'timbergrey', 'bask1'},
    {'timberred', 'bask1'},
    {'timberfawn', 'bask1'},
    {'timberhike', 'bask1'},
    {'cowboyboot', 'biker'},
    {'biker', 'biker'},
    {'sneakskin', 'biker'},
    {'shoedressblk', 'shoe'},
    {'shoedressbrn', 'shoe'},
    {'shoespatz', 'shoe'},
  },
}
